version: '3.6'
services:
  postgres:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: jahbaf
    volumes:
      - postgresql:/var/lib/postgresql/data
      
volumes:
  postgresql: