version: '3'
services:
  postgres:
    image: postgres:12.1
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10 
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/postgresql/data
  front:
    build:
      context: ../2109-wns-remote3-jahbaf-client
      dockerfile: Dockerfile.dev
    container_name: front
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - back
    volumes:
      - ../2109-wns-remote3-jahbaf-client:/app
  back:
    build: ./
    container_name: back
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4004/graphql?query=%7B__typename%7D || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 6
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app