version: '3'
services:
  postgres:
    image: postgres:12.1
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    volumes:
      - ./data/postgre:/postgresql/data
  front:
    image: jahbaf-client
    ports:
      - "3000:3000"
    depends_on:
      back:
        condition: service_healthy
    volumes:
      - ../2109-wns-remote3-jahbaf-client:/app/front
  back:
    image: jahbaf-back
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4004 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10 
    environment:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    ports:
      - "4004:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app/back