version: '3'
services:
  postgres:
    image: postgres:12.1
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10 
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - ./data/postgres:/postgresql/data
